import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: {
    default: "Sachin Khoja | Full Stack Developer & Software Engineer | BitsAndBots - Backend, Next.js, AI, LLM, Scalable systems",
    template: "%s | Sachin Khoja - Full Stack Developer | BitsAndBots"
  },
  description: "Sachin Khoja is a passionate Full Stack Developer and Software Engineer at BitsAndBots, specializing in modern web development, React, Next.js, Node.js, and innovative software solutions. Explore my portfolio of cutting-edge projects and technical expertise.",
  keywords: [
    "Bits and Bots",
    "Bits and Bots AI",
    "Bits and Bots Backend",
    "Bits and Bots Frontend",
    "Bits and Bots Full Stack",
    "Bits and Bots Software Engineer",
    "Bits and Bots Developer",
    "Bits and Bots by Sachin Khoja",
    "Bit and bot by Sachin Khoja",
    "Bit and Bot",
    "Utilties by Bits and Bots",
    "Bits and Bots Utilities",
    "Bits and Bots Utilities by Sachin Khoja",
    "Bits and Bots Utilities by Sachin Khoja",
    "Finance by Bits and Bots",
    "Finance by Bits and Bots by Sachin Khoja",
    "Finance by Bits and Bots by Sachin Khoja",
    "Stock Market by Bits and Bots",
    "Nifty by Bits and Bots",
    "Mutual Funds by Bits and Bots",
    "Finance by Bits and Bots",
    "Finance by Bits and Bots by Sachin Khoja",
    "Finance by Bits and Bots by Sachin Khoja",
    "Sachin Khoja",
    "AI by Bits and Bots",
    "LLM projects by Bits and Bots",
    "AI Agent by Bits and Bots",
    "AI Agent by Bits and Bots by Sachin Khoja",
    "AI Agent by Bits and Bots by Sachin Khoja",
    "RAG by Bits and Bots",
    "RAG by Bits and Bots by Sachin Khoja",
    "RAG by Bits and Bots by Sachin Khoja",
    "BitsAndBots",
    "Full Stack Developer",
    "Software Engineer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "JavaScript Expert",
    "TypeScript Developer",
    "Web Development",
    "Frontend Developer",
    "Backend Developer",
    "Software Development",
    "Portfolio",
    "Tech Innovation",
    "Programming",
    "Software Solutions",
    "Modern Web Apps",
    "Responsive Design",
    "API Development",
    "MongoDB Developer",
    "PostgreSQL Expert",
    "MySQL Database",
    "Express.js",
    "React Native",
    "Mobile App Development",
    "UI/UX Design",
    "Git Version Control",
    "AWS Cloud Services",
    "Docker Containerization",
    "Microservices Architecture",
    "GraphQL API",
    "REST API Development",
    "Agile Development",
    "Scrum Master",
    "DevOps Engineer",
    "CI/CD Pipeline",
    "Test Driven Development",
    "Code Review",
    "Performance Optimization",
    "SEO Optimization",
    "Progressive Web Apps",
    "Single Page Applications",
    "Server Side Rendering",
    "Static Site Generation",
    "Jamstack Architecture",
    "Headless CMS",
    "E-commerce Development",
    "Payment Gateway Integration",
    "Real-time Applications",
    "WebSocket Implementation",
    "Data Visualization",
    "Machine Learning Integration",
    "AI Implementation",
    "Blockchain Development",
    "Smart Contracts",
    "Web3 Development",
    "Cryptocurrency Integration",
    "Fintech Solutions",
    "Healthcare Software",
    "EdTech Applications",
    "SaaS Development",
    "B2B Solutions",
    "B2C Applications",
    "Startup Technology",
    "Enterprise Software",
    "Consulting Services",
    "Technical Leadership",
    "Code Architecture",
    "System Design",
    "Database Design",
    "Security Implementation",
    "Authentication Systems",
    "Authorization Protocols",
    "OAuth Integration",
    "JWT Tokens",
    "Cybersecurity",
    "Data Protection",
    "GDPR Compliance",
    "Accessibility Standards",
    "WCAG Guidelines",
    "Cross-browser Compatibility",
    "Mobile-first Design",
    "Performance Monitoring",
    "Error Tracking",
    "Analytics Integration",
    "A/B Testing",
    "Conversion Optimization",
    "Digital Marketing",
    "Growth Hacking",
    "User Experience",
    "User Interface",
    "Design Systems",
    "Component Libraries",
    "Storybook Development",
    "Design Tokens",
    "Figma to Code",
    "Prototyping",
    "Wireframing",
    "Information Architecture",
    "Content Strategy",
    "Technical Writing",
    "Documentation",
    "API Documentation",
    "Code Comments",
    "Best Practices",
    "Clean Code",
    "SOLID Principles",
    "Design Patterns",
    "Refactoring",
    "Legacy Code Modernization",
    "Migration Services",
    "Technology Upgrade",
    "Performance Tuning",
    "Scalability Solutions",
    "Load Balancing",
    "Caching Strategies",
    "CDN Implementation",
    "Image Optimization",
    "Bundle Optimization",
    "Lazy Loading",
    "Code Splitting",
    "Tree Shaking",
    "Webpack Configuration",
    "Vite Build Tool",
    "ESLint Configuration",
    "Prettier Code Formatting",
    "Husky Git Hooks",
    "Continuous Integration",
    "Continuous Deployment",
    "GitHub Actions",
    "GitLab CI/CD",
    "Jenkins Pipeline",
    "Kubernetes Orchestration",
    "Terraform Infrastructure",
    "Serverless Architecture",
    "Lambda Functions",
    "Vercel Deployment",
    "Netlify Hosting",
    "Firebase Integration",
    "Supabase Backend",
    "Prisma ORM",
    "Drizzle ORM",
    "tRPC Framework",
    "Zod Validation",
    "React Hook Form",
    "Formik Forms",
    "Yup Validation",
    "Axios HTTP Client",
    "Fetch API",
    "SWR Data Fetching",
    "React Query",
    "Zustand State Management",
    "Redux Toolkit",
    "Context API",
    "Custom Hooks",
    "Higher Order Components",
    "Render Props",
    "Compound Components",
    "Headless Components",
    "Styled Components",
    "Emotion CSS",
    "Tailwind CSS",
    "Chakra UI",
    "Material-UI",
    "Ant Design",
    "Mantine UI",
    "Framer Motion",
    "GSAP Animation",
    "Lottie Animation",
    "Three.js 3D",
    "WebGL Graphics",
    "Canvas API",
    "SVG Animation",
    "CSS Animations",
    "Intersection Observer",
    "Web Workers",
    "Service Workers",
    "IndexedDB Storage",
    "Local Storage",
    "Session Storage",
    "Cookies Management",
    "Browser APIs",
    "Geolocation API",
    "Camera API",
    "Microphone API",
    "File API",
    "Drag and Drop",
    "Clipboard API",
    "Notification API",
    "Push Notifications",
    "Web Push Protocol",
    "PWA Manifest",
    "Service Worker Caching",
    "Offline Functionality",
    "Background Sync",
    "Web Assembly",
    "Rust Programming",
    "Python Integration",
    "Go Language",
    "Java Backend",
    "C# .NET",
    "PHP Laravel",
    "Ruby on Rails",
    "Django Framework",
    "Flask Microframework",
    "FastAPI Python",
    "Spring Boot",
    "NestJS Framework",
    "Fastify Framework",
    "Koa.js Framework",
    "Hapi.js Framework",
    "Socket.io Real-time",
    "WebRTC Communication",
    "Peer-to-peer Networking",
    "Electron Desktop Apps",
    "Tauri Desktop Apps",
    "React Native Apps",
    "Expo Framework",
    "Flutter Development",
    "Ionic Framework",
    "Cordova PhoneGap",
    "Progressive Web Apps",
    "Hybrid Mobile Apps",
    "Native Mobile Development",
    "iOS Development",
    "Android Development",
    "Swift Programming",
    "Kotlin Programming",
    "Java Android",
    "Objective-C iOS",
    "React Native Navigation",
    "Expo Router",
    "React Navigation",
    "Native Base UI",
    "Tamagui UI",
    "Gluestack UI",
    "NativeWind Styling",
    "Reanimated 3",
    "Gesture Handler",
    "Haptic Feedback",
    "Device Sensors",
    "Camera Integration",
    "Push Notifications",
    "In-App Purchases",
    "App Store Optimization",
    "Google Play Store",
    "App Analytics",
    "Crash Reporting",
    "Performance Monitoring",
    "User Behavior Tracking",
    "Heat Maps",
    "Session Recordings",
    "Feature Flags",
    "A/B Testing",
    "Experimentation",
    "Growth Metrics",
    "Conversion Tracking",
    "Attribution Modeling",
    "Customer Journey",
    "Retention Analysis",
    "Churn Prediction",
    "Lifetime Value",
    "Revenue Optimization",
    "Subscription Models",
    "Freemium Strategy",
    "Product-Market Fit",
    "User Research",
    "Usability Testing",
    "Accessibility Audits",
    "Performance Audits",
    "Security Audits",
    "Code Reviews",
    "Technical Debt",
    "Refactoring Strategies",
    "Modernization Roadmap",
    "Technology Stack",
    "Architecture Decisions",
    "Scalability Planning",
    "Team Leadership",
    "Mentoring Developers",
    "Code Standards",
    "Development Workflow",
    "Agile Methodologies",
    "Sprint Planning",
    "Daily Standups",
    "Retrospectives",
    "Backlog Management",
    "User Stories",
    "Acceptance Criteria",
    "Definition of Done",
    "Estimation Techniques",
    "Velocity Tracking",
    "Burndown Charts",
    "Kanban Boards",
    "Continuous Improvement",
    "Process Optimization",
    "Quality Assurance",
    "Testing Strategies",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Visual Regression Testing",
    "Accessibility Testing",
    "Performance Testing",
    "Load Testing",
    "Stress Testing",
    "Security Testing",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Risk Management",
    "Compliance Requirements",
    "Audit Preparation",
    "Documentation Standards",
    "Knowledge Sharing",
    "Training Programs",
    "Skill Development",
    "Certification Courses",
    "Conference Speaking",
    "Technical Blogging",
    "Open Source Contributions",
    "Community Building",
    "Networking Events",
    "Industry Partnerships",
    "Client Relations",
    "Project Management",
    "Stakeholder Communication",
    "Requirements Gathering",
    "Solution Architecture",
    "Technical Specifications",
    "Proposal Writing",
    "Cost Estimation",
    "Timeline Planning",
    "Resource Allocation",
    "Risk Assessment",
    "Contingency Planning",
    "Change Management",
    "Version Control",
    "Release Management",
    "Deployment Strategies",
    "Blue-Green Deployment",
    "Canary Releases",
    "Feature Toggles",
    "Environment Management",
    "Configuration Management",
    "Secret Management",
    "Monitoring Solutions",
    "Alerting Systems",
    "Incident Response",
    "Disaster Recovery",
    "Backup Strategies",
    "Business Continuity",
    "SLA Management",
    "Performance Metrics",
    "KPI Tracking",
    "Dashboard Creation",
    "Reporting Automation",
    "Data Analytics",
    "Business Intelligence",
    "Decision Support",
    "Strategic Planning",
    "Innovation Management",
    "Technology Trends",
    "Emerging Technologies",
    "Research and Development",
    "Proof of Concept",
    "Minimum Viable Product",
    "Rapid Prototyping",
    "Iterative Development",
    "Feedback Loops",
    "User-Centered Design",
    "Design Thinking",
    "Lean Startup",
    "Product Strategy",
    "Market Analysis",
    "Competitive Intelligence",
    "SWOT Analysis",
    "Value Proposition",
    "Business Model",
    "Revenue Streams",
    "Cost Structure",
    "Go-to-Market Strategy",
    "Launch Planning",
    "Marketing Automation",
    "Sales Funnel",
    "Lead Generation",
    "Customer Acquisition",
    "Retention Strategies",
    "Loyalty Programs",
    "Referral Systems",
    "Viral Marketing",
    "Content Marketing",
    "SEO Strategies",
    "SEM Campaigns",
    "Social Media Marketing",
    "Influencer Partnerships",
    "Email Marketing",
    "Newsletter Campaigns",
    "Drip Campaigns",
    "Personalization",
    "Segmentation",
    "Behavioral Targeting",
    "Predictive Analytics",
    "Recommendation Systems",
    "AI-Powered Features",
    "Machine Learning Models",
    "Natural Language Processing",
    "Computer Vision",
    "Speech Recognition",
    "Chatbot Development",
    "Virtual Assistants",
    "Automation Tools",
    "Workflow Automation",
    "RPA Implementation",
    "Process Mining",
    "Digital Transformation",
    "Legacy Modernization",
    "Cloud Migration",
    "Hybrid Cloud",
    "Multi-Cloud Strategy",
    "Edge Computing",
    "5G Integration",
    "IoT Development",
    "Smart Devices",
    "Wearable Technology",
    "Augmented Reality",
    "Virtual Reality",
    "Mixed Reality",
    "Metaverse Development",
    "NFT Platforms",
    "DeFi Applications",
    "Cryptocurrency Wallets",
    "Blockchain Networks",
    "Smart Contract Auditing",
    "Tokenomics Design",
    "DAO Development",
    "Web3 Protocols",
    "Decentralized Applications",
    "IPFS Integration",
    "Filecoin Storage",
    "Ethereum Development",
    "Solidity Programming",
    "Polygon Network",
    "Binance Smart Chain",
    "Avalanche Network",
    "Solana Development",
    "Cardano Integration",
    "Polkadot Ecosystem",
    "Cosmos Network",
    "Near Protocol",
    "Chainlink Oracles",
    "Layer 2 Solutions",
    "Rollup Technology",
    "State Channels",
    "Sidechains",
    "Cross-Chain Bridges",
    "Interoperability",
    "Consensus Mechanisms",
    "Proof of Stake",
    "Proof of Work",
    "Delegated Proof of Stake",
    "Byzantine Fault Tolerance",
    "Distributed Systems",
    "Peer-to-Peer Networks",
    "Cryptographic Protocols",
    "Hash Functions",
    "Digital Signatures",
    "Zero-Knowledge Proofs",
    "Privacy Coins",
    "Anonymous Transactions",
    "Compliance Solutions",
    "KYC/AML Integration",
    "Regulatory Technology",
    "Financial Services",
    "Banking Solutions",
    "Payment Processing",
    "Remittance Services",
    "Insurance Technology",
    "Lending Platforms",
    "Investment Management",
    "Wealth Management",
    "Trading Platforms",
    "Market Data",
    "Risk Management",
    "Fraud Detection",
    "Credit Scoring",
    "Underwriting Automation",
    "Claims Processing",
    "Regulatory Reporting",
    "Audit Trails",
    "Transaction Monitoring",
    "Sanctions Screening",
    "Anti-Money Laundering",
    "Know Your Customer",
    "Customer Due Diligence",
    "Enhanced Due Diligence",
    "Politically Exposed Persons",
    "Adverse Media Screening",
    "Transaction Limits",
    "Velocity Checks",
    "Anomaly Detection",
    "Behavioral Analysis",
    "Pattern Recognition",
    "Outlier Detection",
    "Statistical Analysis",
    "Time Series Analysis",
    "Forecasting Models",
    "Predictive Modeling",
    "Classification Algorithms",
    "Clustering Techniques",
    "Dimensionality Reduction",
    "Feature Engineering",
    "Data Preprocessing",
    "Data Cleaning",
    "Data Transformation",
    "ETL Processes",
    "Data Pipelines",
    "Stream Processing",
    "Batch Processing",
    "Real-time Analytics",
    "Event-Driven Architecture",
    "Message Queuing",
    "Event Sourcing",
    "CQRS Pattern",
    "Saga Pattern",
    "Circuit Breaker",
    "Bulkhead Pattern",
    "Retry Logic",
    "Exponential Backoff",
    "Rate Limiting",
    "Throttling",
    "Load Shedding",
    "Graceful Degradation",
    "Fault Tolerance",
    "High Availability",
    "Disaster Recovery",
    "Business Continuity",
    "Service Level Agreements",
    "Uptime Monitoring",
    "Health Checks",
    "Heartbeat Monitoring",
    "Circuit Breaker Pattern",
    "Chaos Engineering",
    "Fault Injection",
    "Resilience Testing",
    "Load Testing",
    "Stress Testing",
    "Spike Testing",
    "Volume Testing",
    "Endurance Testing",
    "Scalability Testing",
    "Capacity Planning",
    "Performance Tuning",
    "Bottleneck Analysis",
    "Resource Optimization",
    "Memory Management",
    "CPU Optimization",
    "I/O Optimization",
    "Network Optimization",
    "Database Optimization",
    "Query Optimization",
    "Index Optimization",
    "Caching Strategies",
    "Cache Invalidation",
    "Cache Warming",
    "CDN Configuration",
    "Edge Caching",
    "Browser Caching",
    "Application Caching",
    "Database Caching",
    "Distributed Caching",
    "In-Memory Caching",
    "Redis Caching",
    "Memcached",
    "Hazelcast",
    "Apache Ignite",
    "Caffeine Cache",
    "Ehcache",
    "Guava Cache",
    "Cache Patterns",
    "Cache-Aside",
    "Write-Through",
    "Write-Behind",
    "Refresh-Ahead",
    "Cache Hierarchies",
    "Multi-Level Caching",
    "Cache Coherence",
    "Cache Consistency",
    "Eventually Consistent",
    "Strong Consistency",
    "Weak Consistency",
    "Causal Consistency",
    "Session Consistency",
    "Monotonic Consistency",
    "ACID Properties",
    "BASE Properties",
    "CAP Theorem",
    "Consistency Models",
    "Distributed Consensus",
    "Raft Algorithm",
    "Paxos Algorithm",
    "Byzantine Generals",
    "Leader Election",
    "Split-Brain Resolution",
    "Quorum Systems",
    "Vector Clocks",
    "Lamport Timestamps",
    "Conflict Resolution",
    "Merge Strategies",
    "Operational Transformation",
    "Conflict-Free Replicated Data Types",
    "Collaborative Editing",
    "Real-time Collaboration",
    "Synchronization Protocols",
    "Distributed Locking",
    "Pessimistic Locking",
    "Optimistic Locking",
    "Lock-Free Algorithms",
    "Wait-Free Algorithms",
    "Concurrent Programming",
    "Parallel Processing",
    "Multi-Threading",
    "Thread Pools",
    "Async/Await",
    "Promises",
    "Callbacks",
    "Event Loops",
    "Non-Blocking I/O",
    "Reactive Programming",
    "Observer Pattern",
    "Publish-Subscribe",
    "Event-Driven Programming",
    "Functional Programming",
    "Lambda Functions",
    "Higher-Order Functions",
    "Pure Functions",
    "Immutability",
    "Lazy Evaluation",
    "Currying",
    "Partial Application",
    "Function Composition",
    "Monads",
    "Functors",
    "Applicatives",
    "Category Theory",
    "Type Theory",
    "Static Typing",
    "Dynamic Typing",
    "Type Inference",
    "Generics",
    "Polymorphism",
    "Inheritance",
    "Composition",
    "Encapsulation",
    "Abstraction",
    "Interfaces",
    "Abstract Classes",
    "Dependency Injection",
    "Inversion of Control",
    "Factory Pattern",
    "Builder Pattern",
    "Singleton Pattern",
    "Observer Pattern",
    "Strategy Pattern",
    "Command Pattern",
    "Decorator Pattern",
    "Adapter Pattern",
    "Facade Pattern",
    "Proxy Pattern",
    "MVC Pattern",
    "MVP Pattern",
    "MVVM Pattern",
    "Flux Architecture",
    "Redux Pattern",
    "Unidirectional Data Flow",
    "State Management",
    "Component Architecture",
    "Modular Design",
    "Separation of Concerns",
    "Single Responsibility",
    "Open/Closed Principle",
    "Liskov Substitution",
    "Interface Segregation",
    "Dependency Inversion",
    "DRY Principle",
    "KISS Principle",
    "YAGNI Principle",
    "Code Smells",
    "Technical Debt",
    "Refactoring Techniques",
    "Extract Method",
    "Extract Class",
    "Move Method",
    "Rename Variable",
    "Replace Magic Number",
    "Consolidate Duplicate Code",
    "Simplify Conditional",
    "Replace Nested Conditional",
    "Decompose Conditional",
    "Replace Parameter with Method",
    "Introduce Parameter Object",
    "Preserve Whole Object",
    "Replace Array with Object",
    "Replace Type Code with Class",
    "Replace Type Code with Subclasses",
    "Replace Type Code with State",
    "Replace Subclass with Fields",
    "Replace Inheritance with Delegation",
    "Replace Delegation with Inheritance",
    "Tease Apart Inheritance",
    "Extract Hierarchy",
    "Collapse Hierarchy",
    "Form Template Method",
    "Replace Inheritance with Delegation",
    "Replace Delegation with Inheritance",
    "Extract Module",
    "Inline Module",
    "Extract Package",
    "Inline Package",
    "Move Class",
    "Move Field",
    "Extract Interface",
    "Collapse Duplicate Interfaces",
    "Introduce Local Extension",
    "Introduce Foreign Method",
    "Replace Data Value with Object",
    "Change Value to Reference",
    "Change Reference to Value",
    "Replace Magic Number with Symbolic Constant",
    "Encapsulate Field",
    "Encapsulate Collection",
    "Replace Record with Data Class",
    "Replace Type Code with Polymorphism",
    "Replace Conditional with Polymorphism",
    "Introduce Null Object",
    "Introduce Assertion",
    "Separate Query from Modifier",
    "Parameterize Method",
    "Replace Parameter with Explicit Methods",
    "Preserve Whole Object",
    "Replace Parameter with Method Call",
    "Introduce Parameter Object",
    "Remove Setting Method",
    "Hide Method",
    "Replace Constructor with Factory Method",
    "Replace Error Code with Exception",
    "Replace Exception with Test",
    "Pull Up Field",
    "Pull Up Method",
    "Pull Up Constructor Body",
    "Push Down Method",
    "Push Down Field",
    "Extract Subclass",
    "Extract Superclass",
    "Extract Interface",
    "Collapse Hierarchy",
    "Form Template Method",
    "Replace Inheritance with Delegation",
    "Replace Delegation with Inheritance"
  ],
  authors: [{ name: "Sachin Khoja", url: "https://bitsandbots.in" }],
  creator: "Sachin Khoja",
  publisher: "BitsAndBots",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://bitsandbots.in",
    siteName: "Sachin Khoja | BitsAndBots",
    title: "Sachin Khoja | BitsAndBots - Full Stack Developer & Software Engineer",
    description: "Explore the portfolio of Sachin Khoja, a passionate Full Stack Developer at BitsAndBots. Discover innovative software projects, technical expertise, and modern web development solutions.",
    images: [
      {
        url: "/logo.png",
        width: 1200,
        height: 630,
        alt: "Sachin Khoja - BitsAndBots Portfolio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Sachin Khoja | BitsAndBots - Full Stack Developer",
    description: "Passionate Full Stack Developer at BitsAndBots specializing in modern web development and innovative software solutions.",
    images: ["/logo.png"],
    creator: "@sachinkhoja",
  },
  icons: {
    icon: [
      { url: "/favicon/favicon.ico", sizes: "any" },
      { url: "/favicon/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon/favicon-96x96.png", sizes: "96x96", type: "image/png" },
    ],
    apple: [
      { url: "/favicon/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      {
        rel: "mask-icon",
        url: "/favicon/favicon.svg",
        color: "#000000",
      },
    ],
  },
  manifest: "/favicon/site.webmanifest",
  metadataBase: new URL("https://bitsandbots.in"),
  alternates: {
    canonical: "https://bitsandbots.in",
  },
  category: "technology",
  classification: "portfolio",
  verification: {
    google: "your-google-verification-code", // Replace with actual verification code
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange={false}
        >
          <div className="relative min-h-screen">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
